included:
  - CICDPipelinePOC
  - CICDPipelinePOCTests

excluded:
  - CICDPipelinePOCUITests
  - build
  - fastlane/test_output
  - vendor

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - sorted_imports

analyzer_rules:
  - unused_import

line_length:
  warning: 160
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id

reporter: xcode
